name: Export to Web

on:
    push:
        branches:
            - main

jobs:
    export:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 14
                
            - name: Install love.js
              run: npm install -g love.js
            
            - name: Package a web build
              run: |
                cd main
                zip -9 -r game.love .
                cd ..
                love.js ./main/game.love web -t "game" -c
            
            - name: Add, commit and push
              run: |
                cd web
                git add .
                git commit -m "Auto package web build on push" || true
                git push

              